#### opening hours app for Glasgow
## Skip DOWN 231 lines to see the actual code
## I'm just embedding the data in this file here to make deployment easier
openinghours <- structure(list(FACILITY.TYPE = structure(c(8L, 8L, 8L, 8L, 8L, 
                                                           8L, 8L, 8L, 8L, 8L, 8L, 8L, 8L, 8L, 8L, 8L, 8L, 8L, 8L, 8L, 8L, 
                                                           8L, 8L, 8L, 8L, 8L, 8L, 8L, 8L, 8L, 6L, 6L, 6L, 6L, 6L, 6L, 6L, 
                                                           6L, 6L, 6L, 6L, 10L, 10L, 10L, 10L, 10L, 10L, 9L, 9L, 9L, 9L, 
                                                           9L, 9L, 9L, 9L, 9L, 9L, 9L, 7L, 7L, 7L, 7L, 7L, 7L, 7L, 7L, 7L, 
                                                           4L, 4L, 4L, 4L, 4L, 4L, 4L, 4L, 4L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 
                                                           3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 
                                                           3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 5L, 5L, 5L, 1L, 1L, 2L, 
                                                           2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 
                                                           2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L), .Label = c("Arts", 
                                                                                                                           "Community Facilities", "Libraries", "Museums", "Music", "Sport - Bowling Greens", 
                                                                                                                           "Sport - Football Centres", "Sport - Glasgow Club", "Sport - Golf", 
                                                                                                                           "Sport - Tennis"), class = "factor"), FACILITY.NAME = structure(c(7L, 
                                                                                                                                                                                             11L, 18L, 21L, 26L, 29L, 34L, 35L, 37L, 38L, 40L, 44L, 48L, 55L, 
                                                                                                                                                                                             58L, 59L, 62L, 81L, 84L, 88L, 90L, 91L, 97L, 101L, 120L, 126L, 
                                                                                                                                                                                             127L, 133L, 140L, 144L, 1L, 12L, 32L, 64L, 69L, 77L, 83L, 108L, 
                                                                                                                                                                                             124L, 132L, 138L, 33L, 50L, 65L, 71L, 111L, 121L, 2L, 67L, 74L, 
                                                                                                                                                                                             76L, 78L, 118L, 57L, 70L, 109L, 110L, 139L, 8L, 43L, 54L, 60L, 
                                                                                                                                                                                             79L, 98L, 125L, 129L, 135L, 16L, 45L, 46L, 63L, 96L, 107L, 113L, 
                                                                                                                                                                                             119L, 131L, 3L, 4L, 10L, 15L, 17L, 20L, 24L, 28L, 31L, 36L, 39L, 
                                                                                                                                                                                             47L, 49L, 51L, 56L, 61L, 68L, 73L, 82L, 85L, 86L, 92L, 94L, 100L, 
                                                                                                                                                                                             102L, 104L, 105L, 112L, 115L, 123L, 128L, 141L, 143L, 41L, 22L, 
                                                                                                                                                                                             53L, 136L, 137L, 30L, 66L, 89L, 93L, 142L, 19L, 23L, 103L, 52L, 
                                                                                                                                                                                             72L, 130L, 5L, 9L, 13L, 80L, 87L, 106L, 114L, 117L, 6L, 14L, 
                                                                                                                                                                                             116L, 122L, 134L, 42L, 27L, 95L, 99L, 25L, 75L), .Label = c("Alexander Park Bowling", 
                                                                                                                                                                                                                                                         "Alexandra Golf Course", "Anniesland Library ", "Baillieston Library ", 
                                                                                                                                                                                                                                                         "Balgrayhill T.H.", "Barlanark C.C.", "Barlia Complex", "Barlia Football Centre", 
                                                                                                                                                                                                                                                         "Barmulloch C.C.", "Barmulloch Library ", "Bellahouston", "Bellahouston Park Bowling", 
                                                                                                                                                                                                                                                         "Bellcraig C.C.", "Bluevale N.C.", "Bridgeton Library", "Burrell ", 
                                                                                                                                                                                                                                                         "Cardonald Library ", "Castlemilk", "Castlemilk C.C.", "Castlemilk Library ", 
                                                                                                                                                                                                                                                         "Castlemilk Pool", "City Halls", "Couper Institute", "Couper Institute ", 
                                                                                                                                                                                                                                                         "Cranhill Beacon", "Crownpoint Sports Centre", "Darnley C.C.", 
                                                                                                                                                                                                                                                         "Dennistoun Library ", "Donald Dewar Leisure Centre", "Drumchapel C.C.", 
                                                                                                                                                                                                                                                         "Drumchapel Library ", "Drumchapel Park Bowling", "Drumchapel Park Tennis", 
                                                                                                                                                                                                                                                         "Drumchapel Pool", "Drumoyne CSC", "Easterhouse/Bridge Library ", 
                                                                                                                                                                                                                                                         "Easterhouse Pool @ the Bridge", "Easterhouse Sports Centre", 
                                                                                                                                                                                                                                                         "Elder Park ", "Emirates Arena", "Fruit Market", "Garrowhill Hall", 
                                                                                                                                                                                                                                                         "Glasgow Green Football Centre", "Glasgow National Hockey Centre", 
                                                                                                                                                                                                                                                         "GMRC", "GOMA", "GOMA Library ", "Gorbals Leisure Centre", "Gorbals Library ", 
                                                                                                                                                                                                                                                         "Gorbals Tennis Centre", "Govanhill Library ", "Govanhill N.C.", 
                                                                                                                                                                                                                                                         "GRCH", "Greenfield Football Centre", "Haghill", "Hillhead Library ", 
                                                                                                                                                                                                                                                         "Hogganfield Pitch and Putt", "Holyrood Sports Centre", "Ibrox Community Complex", 
                                                                                                                                                                                                                                                         "Ibrox Football Centre", "Ibrox Library ", "John Paul Community SC", 
                                                                                                                                                                                                                                                         "Kelvingrove", "Kelvingrove\xa0Lawn Bowls Centre", "Kelvingrove Park Tennis", 
                                                                                                                                                                                                                                                         "Knightswood C.C.", "Knightswood Golf Course", "Knightswood Library ", 
                                                                                                                                                                                                                                                         "Knightswood Park Bowling", "Knightswood Park Pitch and Putt", 
                                                                                                                                                                                                                                                         "Knightswood Park Tennis", "Langside Halls", "Langside Library ", 
                                                                                                                                                                                                                                                         "Lethamhill Golf Course", "Linn Park", "Linn Park Golf Course", 
                                                                                                                                                                                                                                                         "Lister Street Bowling", "Littlehill Golf Course", "Lochend Football Centre", 
                                                                                                                                                                                                                                                         "Maryhill C.C.", "Maryhill LC", "Maryhill Library ", "Maryhill Park Bowling", 
                                                                                                                                                                                                                                                         "Milton Community Campus", "Milton Library ", "Mitchell Library ", 
                                                                                                                                                                                                                                                         "Molendinar C.C.", "Nethercraigs", "Netherton C.C.", "North Woodside Leisure Centre", 
                                                                                                                                                                                                                                                         "Palace of Art", "Parkhead Library ", "Partick B.H.", "Partick Library ", 
                                                                                                                                                                                                                                                         "Penilee C.C.", "People's Palace", "Petershill Park", "Peterson Park Football Centre", 
                                                                                                                                                                                                                                                         "Pollok C.C.", "Pollok Library ", "Pollok Pool", "Pollokshaws Library ", 
                                                                                                                                                                                                                                                         "Pollokshields C.C.", "Pollokshields Library ", "Possilpark Library ", 
                                                                                                                                                                                                                                                         "Possilpoint C.C.", "Provand's Lordship", "Queen's Park Bowling", 
                                                                                                                                                                                                                                                         "Queen's Park Pitch and Putt", "Queen's Park Putting Green", 
                                                                                                                                                                                                                                                         "Queen's Park Tennis", "Riddrie Library ", "Riverside", "Roystonhill R.C.", 
                                                                                                                                                                                                                                                         "Royston Library ", "Ruchazie C.C.", "Ruchill C.C.", "Ruchill Golf Course", 
                                                                                                                                                                                                                                                         "Scotland Street", "Scotstoun Leisure Centre", "Scotstoun Tennis Centre", 
                                                                                                                                                                                                                                                         "Shettleston C.C.", "Shettleston Library ", "Spingburn Park Bowling", 
                                                                                                                                                                                                                                                         "Springburn Football Centre", "Springburn Leisure Centre", "Springburn Leisure Centre - Pool", 
                                                                                                                                                                                                                                                         "Springburn Library ", "Stepford Football Centre", "St Francis Centre", 
                                                                                                                                                                                                                                                         "St. Mungo's", "Temple Bowling", "Tollcross", "Tollcross Y.C.", 
                                                                                                                                                                                                                                                         "Toryglen Regional Football Centre", "Tramway", "Trongate 103", 
                                                                                                                                                                                                                                                         "Victoria Park Bowling", "Victoria Park Putting Green", "Whitehill Pool", 
                                                                                                                                                                                                                                                         "Whiteinch Library ", "Woodside Hall", "Woodside Library ", "Yoker Sports Centre"
                                                                                                                                                                                             ), class = "factor"), MONDAY = structure(c(5L, 13L, 5L, 48L, 
                                                                                                                                                                                                                                        18L, 48L, 47L, 46L, 19L, 5L, 13L, 36L, 17L, 2L, 11L, 10L, 12L, 
                                                                                                                                                                                                                                        23L, 46L, 48L, 5L, 14L, 46L, 44L, 15L, 5L, 5L, 15L, 23L, 46L, 
                                                                                                                                                                                                                                        7L, 7L, 7L, 4L, 7L, 8L, 7L, 7L, 7L, 7L, 6L, 5L, 48L, 48L, 5L, 
                                                                                                                                                                                                                                        5L, 47L, 24L, 24L, 24L, 24L, 24L, 24L, 7L, 7L, 7L, 7L, 6L, 5L, 
                                                                                                                                                                                                                                        46L, 46L, 10L, 12L, 1L, 46L, 9L, 46L, 3L, 3L, 3L, 3L, 49L, 49L, 
                                                                                                                                                                                                                                        3L, 49L, 49L, 4L, 4L, 3L, 4L, 4L, 4L, 3L, 4L, 3L, 47L, 3L, 3L, 
                                                                                                                                                                                                                                        47L, 4L, 4L, 4L, 4L, 4L, 3L, 3L, 47L, 4L, 4L, 4L, 4L, 4L, 3L, 
                                                                                                                                                                                                                                        4L, 3L, 4L, 4L, 3L, 4L, 1L, 1L, 1L, 49L, 49L, 37L, 45L, 34L, 
                                                                                                                                                                                                                                        26L, 1L, 22L, 30L, 32L, 20L, 25L, 43L, 38L, 41L, 22L, 21L, 41L, 
                                                                                                                                                                                                                                        33L, 41L, 29L, 27L, 39L, 39L, 35L, 31L, 40L, 16L, 42L, 28L, 1L, 
                                                                                                                                                                                                                                        49L), .Label = c("", "10am - 10pm", "10am - 5pm", "10am - 8pm", 
                                                                                                                                                                                                                                                         "10am - 9pm", "11am - 8pm", "11am - 9pm", "1.30pm - 9pm", "1pm - 10pm", 
                                                                                                                                                                                                                                                         "2pm - 8pm", "4pm - 9pm", "5pm - 9pm", "6.30am - 10pm", "6.45am - 9pm", 
                                                                                                                                                                                                                                                         "7.00am - 10pm", "7:00am - 8:00pm", "7.00am - 8pm", "7.15am - 9.30pm", 
                                                                                                                                                                                                                                                         "7.30am - 8pm", "7.30am - 9.00am", "7.30am - 9.30pm", "7.30am - 9.45pm", 
                                                                                                                                                                                                                                                         "7.30am - 9pm", "7am-9pm ", "8.00am - 10.00pm", "8.00am - 10.30pm", 
                                                                                                                                                                                                                                                         "8.00am - 9.00pm", "8.00am - 9:15pm", "8.00am - 9.15pm", "8.00am - 9.30pm", 
                                                                                                                                                                                                                                                         "8.30am - 6.15pm", "8.30am - 7.15pm", "8.30am - 8.30pm", "8.30am - 9.00pm", 
                                                                                                                                                                                                                                                         "8.45am - 9.45pm", "8am - 10pm", "9.00am - 5.00pm", "9.00am - 8.30pm", 
                                                                                                                                                                                                                                                         "9.00am - 9.00pm", "9.00am -9.00pm", "9.00am - 9.15pm", "9:00am - 9:30pm", 
                                                                                                                                                                                                                                                         "9.00am - 9.30pm", "9.30am - 7.30pm", "9.30am - 9.30pm", "9am - 10pm", 
                                                                                                                                                                                                                                                         "9am - 8pm", "9am - 9pm", "CLOSED"), class = "factor"), TUESDAY = structure(c(2L, 
                                                                                                                                                                                                                                                                                                                                       15L, 52L, 19L, 21L, 52L, 51L, 50L, 22L, 27L, 15L, 39L, 5L, 2L, 
                                                                                                                                                                                                                                                                                                                                       13L, 11L, 14L, 5L, 50L, 12L, 49L, 16L, 50L, 46L, 17L, 26L, 26L, 
                                                                                                                                                                                                                                                                                                                                       17L, 26L, 20L, 7L, 7L, 7L, 4L, 7L, 8L, 7L, 7L, 7L, 7L, 6L, 5L, 
                                                                                                                                                                                                                                                                                                                                       5L, 52L, 5L, 5L, 51L, 28L, 28L, 28L, 28L, 28L, 28L, 7L, 7L, 7L, 
                                                                                                                                                                                                                                                                                                                                       7L, 6L, 2L, 50L, 9L, 11L, 14L, 1L, 50L, 10L, 50L, 3L, 3L, 3L, 
                                                                                                                                                                                                                                                                                                                                       3L, 3L, 3L, 3L, 3L, 3L, 4L, 4L, 4L, 4L, 4L, 4L, 4L, 4L, 4L, 51L, 
                                                                                                                                                                                                                                                                                                                                       4L, 3L, 51L, 4L, 4L, 4L, 4L, 4L, 4L, 4L, 51L, 4L, 4L, 4L, 4L, 
                                                                                                                                                                                                                                                                                                                                       4L, 4L, 4L, 4L, 4L, 4L, 4L, 4L, 1L, 1L, 1L, 47L, 3L, 53L, 48L, 
                                                                                                                                                                                                                                                                                                                                       36L, 30L, 1L, 25L, 32L, 37L, 23L, 29L, 45L, 40L, 43L, 24L, 24L, 
                                                                                                                                                                                                                                                                                                                                       43L, 35L, 53L, 32L, 31L, 41L, 41L, 38L, 34L, 42L, 18L, 44L, 33L, 
                                                                                                                                                                                                                                                                                                                                       1L, 53L), .Label = c("", "10am - 10pm", "10am - 5pm", "10am - 8pm", 
                                                                                                                                                                                                                                                                                                                                                            "10am - 9pm", "11am - 8pm", "11am - 9pm", "1.30pm - 9pm", "1pm - 10pm", 
                                                                                                                                                                                                                                                                                                                                                            "2pm - 10pm", "2pm - 8pm", "2pm - 9pm", "4pm - 9pm", "5pm - 9pm", 
                                                                                                                                                                                                                                                                                                                                                            "6.30am - 10pm", "6.45am - 9pm", "7.00am - 10pm", "7:00am - 9:00pm", 
                                                                                                                                                                                                                                                                                                                                                            "7.00am - 9pm", "7.15am - 10pm", "7.15am - 9.30pm", "7.30am - 8pm", 
                                                                                                                                                                                                                                                                                                                                                            "7.30am - 9.00am", "7.30am - 9.30pm", "7.30am - 9.45pm", "7.30am - 9pm", 
                                                                                                                                                                                                                                                                                                                                                            "7.45am - 9pm", "7am-9pm ", "8.00am - 10.00pm", "8.00am - 10.30pm", 
                                                                                                                                                                                                                                                                                                                                                            "8.00am - 8.45pm", "8.00am - 9.15pm", "8.00am - 9:30pm", "8.30am - 8.15pm", 
                                                                                                                                                                                                                                                                                                                                                            "8.30am - 8.30pm", "8.30am - 9.00pm", "8.30am - 9.15pm", "8.45am - 9.45pm", 
                                                                                                                                                                                                                                                                                                                                                            "8am - 10pm", "9.00am - 8.30pm", "9.00am - 9.00pm", "9.00am -9.00pm", 
                                                                                                                                                                                                                                                                                                                                                            "9.00am - 9.15pm", "9:00am - 9:30pm", "9.00am - 9.30pm", "9.30am - 7.30pm", 
                                                                                                                                                                                                                                                                                                                                                            "9.30am - 8pm", "9.30am - 9.30pm", "9.30am - 9pm", "9am - 10pm", 
                                                                                                                                                                                                                                                                                                                                                            "9am - 8pm", "9am - 9pm", "CLOSED"), class = "factor"), WEDNESDAY = structure(c(3L, 
                                                                                                                                                                                                                                                                                                                                                                                                                                            15L, 50L, 6L, 20L, 50L, 49L, 48L, 21L, 12L, 15L, 38L, 19L, 3L, 
                                                                                                                                                                                                                                                                                                                                                                                                                                            13L, 11L, 14L, 24L, 48L, 50L, 25L, 16L, 48L, 45L, 17L, 24L, 50L, 
                                                                                                                                                                                                                                                                                                                                                                                                                                            17L, 6L, 48L, 8L, 8L, 8L, 5L, 8L, 9L, 8L, 8L, 8L, 8L, 7L, 6L, 
                                                                                                                                                                                                                                                                                                                                                                                                                                            50L, 50L, 6L, 6L, 49L, 26L, 26L, 26L, 26L, 26L, 26L, 8L, 8L, 
                                                                                                                                                                                                                                                                                                                                                                                                                                            8L, 8L, 7L, 3L, 48L, 10L, 11L, 14L, 1L, 48L, 10L, 48L, 4L, 4L, 
                                                                                                                                                                                                                                                                                                                                                                                                                                            4L, 4L, 4L, 4L, 4L, 4L, 4L, 4L, 4L, 4L, 4L, 4L, 4L, 4L, 4L, 4L, 
                                                                                                                                                                                                                                                                                                                                                                                                                                            49L, 4L, 4L, 49L, 4L, 4L, 4L, 4L, 4L, 4L, 4L, 49L, 4L, 4L, 4L, 
                                                                                                                                                                                                                                                                                                                                                                                                                                            4L, 4L, 4L, 4L, 4L, 4L, 4L, 4L, 4L, 1L, 1L, 1L, 46L, 4L, 51L, 
                                                                                                                                                                                                                                                                                                                                                                                                                                            47L, 34L, 28L, 1L, 23L, 29L, 35L, 22L, 27L, 44L, 39L, 42L, 23L, 
                                                                                                                                                                                                                                                                                                                                                                                                                                            23L, 42L, 36L, 2L, 32L, 31L, 40L, 40L, 37L, 33L, 41L, 18L, 43L, 
                                                                                                                                                                                                                                                                                                                                                                                                                                            30L, 1L, 51L), .Label = c("", "10.30am - 9.15pm", "10am - 10pm", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      "10am - 5pm", "10am - 8pm", "10am - 9pm", "11am - 8pm", "11am - 9pm", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      "1.30pm - 9pm", "1pm - 10pm", "2pm - 8pm", "2pm - 9pm", "4pm - 9pm", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      "5pm - 9pm", "6.30am - 10pm", "6.45am - 9pm", "7.00am - 10pm", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      "7:00am - 9:00pm", "7.00am - 9pm", "7.15am - 9.30pm", "7.30am - 8pm", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      "7.30am - 9.00am", "7.30am - 9.45pm", "7.30am - 9pm", "7.45am - 9pm", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      "7am-9pm ", "8.00am - 10.00pm", "8.00am - 10.30pm", "8.00am - 11.15pm", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      "8.00am - 8:45pm", "8.00am - 9.00pm", "8.00am - 9.15pm", "8.30am - 8.15pm", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      "8.30am - 9.00pm", "8.30am - 9.15pm", "8.30am - 9.30pm", "8.45am - 8.15pm", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      "8am - 10pm", "9.00am - 8.30pm", "9.00am - 9.00pm", "9.00am -9.00pm", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      "9.00am - 9.15pm", "9:00am - 9:30pm", "9.00am - 9.30pm", "9.30am - 7.30pm", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      "9.30am - 8pm", "9.30am - 9.30pm", "9am - 10pm", "9am - 8pm", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      "9am - 9pm", "CLOSED"), class = "factor"), THURSDAY = structure(c(5L, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        17L, 54L, 20L, 22L, 54L, 14L, 52L, 23L, 28L, 17L, 39L, 20L, 2L, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        15L, 14L, 16L, 27L, 52L, 54L, 51L, 18L, 52L, 48L, 2L, 27L, 27L, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        2L, 27L, 21L, 9L, 9L, 9L, 4L, 9L, 10L, 9L, 7L, 9L, 9L, 6L, 5L, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        54L, 54L, 5L, 5L, 53L, 29L, 29L, 29L, 29L, 29L, 29L, 9L, 9L, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        9L, 7L, 6L, 5L, 52L, 11L, 14L, 16L, 1L, 52L, 13L, 52L, 3L, 3L, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        4L, 3L, 3L, 3L, 3L, 3L, 3L, 8L, 8L, 12L, 4L, 4L, 8L, 12L, 8L, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        12L, 53L, 12L, 4L, 53L, 8L, 4L, 8L, 8L, 8L, 12L, 12L, 53L, 8L, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        8L, 8L, 8L, 8L, 12L, 8L, 12L, 8L, 8L, 12L, 8L, 1L, 1L, 1L, 49L, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        3L, 55L, 50L, 38L, 31L, 1L, 26L, 34L, 37L, 24L, 30L, 46L, 40L, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        44L, 25L, 26L, 41L, 36L, 55L, 34L, 32L, 42L, 42L, 47L, 35L, 43L, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        19L, 45L, 33L, 1L, 55L), .Label = c("", "10am - 10pm", "10am - 5pm", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "10am - 8pm", "10am - 9pm", "11am - 8pm", "11am - 9pm", "12noon - 8pm", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "12pm - 9pm", "1.30pm - 9pm", "1pm - 10pm", "1pm - 8pm", "2pm - 10pm", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "2pm - 8pm", "4pm - 9pm", "5pm - 9pm", "6.30am - 10pm", "6.45am - 9pm", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "7:00am - 9:00pm", "7.00am - 9pm", "7.15am - 10pm", "7.15am - 9.30pm", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "7.30am - 8pm", "7.30am - 9.00am", "7.30am - 9.30pm", "7.30am - 9.45pm", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "7.30am - 9pm", "7.45am - 9pm", "7am-9pm ", "8.00am - 10.00pm", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "8.00am - 10.30pm", "8.00am - 8.45pm", "8.00am - 9:15pm", "8.00am - 9.15pm", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "8.30am - 8.15pm", "8.30am - 8.30pm", "8.30am - 8.45pm", "8.30am - 9.00pm", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "8am - 10pm", "9.00am - 8.30pm", "9.00am - 8.45pm", "9.00am - 9.00pm", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "9.00am -9.00pm", "9.00am - 9.15pm", "9:00am - 9:30pm", "9.00am - 9.30pm", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "9.00am - 9.45pm", "9.30am - 7.30pm", "9.30am - 8pm", "9.30am - 9.30pm", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "9.30am - 9pm", "9am - 10pm", "9am - 8pm", "9am - 9pm", "CLOSED"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ), class = "factor"), FRIDAY = structure(c(16L, 20L, 57L, 57L, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   25L, 57L, 56L, 57L, 26L, 15L, 20L, 41L, 24L, 2L, 17L, 14L, 19L, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   29L, 57L, 15L, 30L, 21L, 53L, 3L, 22L, 29L, 57L, 22L, 29L, 53L, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   10L, 10L, 10L, 5L, 10L, 15L, 10L, 9L, 10L, 10L, 8L, 6L, 57L, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   57L, 6L, 6L, 56L, 31L, 31L, 31L, 31L, 31L, 31L, 10L, 10L, 10L, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   9L, 8L, 16L, 53L, 12L, 14L, 18L, 1L, 53L, 13L, 53L, 7L, 7L, 7L, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   7L, 7L, 7L, 7L, 7L, 7L, 54L, 54L, 4L, 54L, 54L, 54L, 4L, 54L, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   4L, 54L, 4L, 7L, 54L, 55L, 54L, 54L, 54L, 54L, 4L, 4L, 54L, 54L, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   54L, 54L, 54L, 54L, 4L, 54L, 4L, 54L, 54L, 4L, 54L, 1L, 1L, 1L, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   51L, 4L, 58L, 52L, 38L, 33L, 1L, 28L, 35L, 39L, 27L, 32L, 50L, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   46L, 42L, 28L, 28L, 47L, 39L, 11L, 36L, 34L, 48L, 44L, 40L, 37L, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   49L, 23L, 43L, 45L, 1L, 58L), .Label = c("", "10am - 10pm", "10am - 4pm", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "10am - 5pm", "10am - 8pm", "10am - 9pm", "11am - 5pm", "11am - 8pm", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "11am - 9pm", "12pm - 9pm", "13.15am - 21.15pm", "1pm - 10pm", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "2pm - 10pm", "2pm - 8pm", "2pm - 9pm", "3pm - 8pm", "4pm - 9pm", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "5pm - 8pm", "5pm - 9pm", "6.30am - 10pm", "6.45am - 9pm", "7.00am - 10pm", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "7:00am - 7:00pm", "7.00am - 9pm", "7.15am - 9.30pm", "7.30am - 8pm", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "7.30am - 9.00am", "7.30am - 9.45pm", "7.30am - 9pm", "7.45am - 9pm", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "7am-9pm ", "8.00am - 10.00pm", "8.00am - 10.30pm", "8.00am - 6.00pm", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "8.00am - 7.45pm", "8.00am - 9.15pm", "8.30am - 6.15pm", "8.30am - 9.00pm", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "8.30am - 9.30pm", "8.45am - 5.15pm", "8am - 6pm", "9.00am - 5.00pm", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "9:00am - 7.00pm", "9.00am - 7.00pm", "9.00am - 7:30pm", "9.00am - 8.30pm", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "9.00am - 8.45pm", "9.00am - 9.00pm", "9.00am -9.00pm", "9.00am - 9.30pm", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "9.30am - 8pm", "9.30am - 9.30pm", "9am - 10pm", "9am - 5pm", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "9am - 5pm", "9am - 8pm", "9am - 9pm", "CLOSED"), class = "factor"), 
                               SATURDAY = structure(c(30L, 19L, 6L, 30L, 25L, 31L, 30L, 
                                                      30L, 31L, 6L, 33L, 19L, 30L, 6L, 29L, 31L, 30L, 30L, 31L, 
                                                      31L, 30L, 31L, 31L, 28L, 31L, 30L, 30L, 31L, 30L, 31L, 10L, 
                                                      10L, 10L, 5L, 10L, 34L, 10L, 26L, 10L, 10L, 9L, 33L, 30L, 
                                                      33L, 33L, 33L, 31L, 12L, 12L, 12L, 12L, 12L, 12L, 10L, 10L, 
                                                      10L, 26L, 9L, 5L, 30L, 31L, 18L, 6L, 1L, 31L, 7L, 31L, 6L, 
                                                      6L, 8L, 6L, 6L, 6L, 6L, 6L, 6L, 31L, 31L, 6L, 31L, 31L, 31L, 
                                                      6L, 31L, 6L, 31L, 6L, 6L, 31L, 32L, 31L, 31L, 31L, 31L, 6L, 
                                                      6L, 31L, 31L, 31L, 31L, 31L, 31L, 6L, 31L, 6L, 31L, 31L, 
                                                      6L, 31L, 1L, 1L, 1L, 27L, 6L, 23L, 22L, 34L, 13L, 1L, 22L, 
                                                      14L, 24L, 34L, 15L, 34L, 34L, 4L, 20L, 11L, 34L, 34L, 34L, 
                                                      2L, 34L, 34L, 34L, 17L, 34L, 34L, 34L, 21L, 16L, 1L, 3L), .Label = c("", 
                                                                                                                           "10.00am - 2.00pm", "10.00am - 4.00pm", "10.00am - 5.00pm", 
                                                                                                                           "10am - 4pm", "10am - 5pm", "10am - 6pm", "11am - 5pm", "11am - 7pm", 
                                                                                                                           "12pm - 9pm", "7.30am - 9.45pm", "7am-9pm ", "8.00am - 1.30am", 
                                                                                                                           "8.00am - 3.00pm", "8.00am - 4.00pm", "8.00am - 9:15pm", 
                                                                                                                           "8.30am - 12.30pm", "8.30am - 5pm", "8am - 6pm", "9.00am - 1.30pm", 
                                                                                                                           "9:00am - 4.00pm", "9.00am - 4.00pm", "9.00am - 5.00pm", 
                                                                                                                           "9.30am - 2.30pm", "9.30am - 5:30pm", "9.30am - 7pm", "9.30am - 8pm", 
                                                                                                                           "9am - 3.30pm", "9am - 3pm", "9am - 4pm", "9am - 5pm", "9am - 5pm", 
                                                                                                                           "9am - 6pm", "CLOSED"), class = "factor"), SUNDAY = structure(c(29L, 
                                                                                                                                                                                           30L, 3L, 27L, 22L, 28L, 27L, 27L, 3L, 3L, 31L, 19L, 30L, 
                                                                                                                                                                                           3L, 26L, 28L, 27L, 27L, 28L, 28L, 27L, 18L, 24L, 25L, 31L, 
                                                                                                                                                                                           27L, 27L, 31L, 27L, 29L, 12L, 12L, 12L, 4L, 12L, 32L, 12L, 
                                                                                                                                                                                           12L, 12L, 12L, 6L, 29L, 30L, 29L, 29L, 29L, 30L, 15L, 15L, 
                                                                                                                                                                                           15L, 15L, 15L, 15L, 12L, 12L, 12L, 12L, 6L, 21L, 24L, 29L, 
                                                                                                                                                                                           29L, 3L, 1L, 29L, 3L, 24L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 
                                                                                                                                                                                           5L, 32L, 32L, 32L, 32L, 32L, 32L, 32L, 32L, 32L, 32L, 32L, 
                                                                                                                                                                                           5L, 32L, 32L, 10L, 32L, 32L, 32L, 32L, 32L, 32L, 32L, 32L, 
                                                                                                                                                                                           32L, 32L, 32L, 32L, 32L, 32L, 32L, 32L, 32L, 32L, 1L, 1L, 
                                                                                                                                                                                           1L, 11L, 9L, 32L, 14L, 8L, 32L, 1L, 13L, 16L, 32L, 23L, 17L, 
                                                                                                                                                                                           32L, 32L, 7L, 32L, 20L, 32L, 32L, 32L, 32L, 32L, 32L, 32L, 
                                                                                                                                                                                           32L, 32L, 32L, 32L, 32L, 32L, 1L, 2L), .Label = c("", "10.00am - 4.00pm", 
                                                                                                                                                                                                                                             "10am - 5pm", "10am - 7pm", "11am - 5pm", "11am - 7pm", "12.30pm - 5.00pm", 
                                                                                                                                                                                                                                             "12noon - 4.00pm", "12 noon - 5pm", "12noon - 5pm", "12pm - 6pm", 
                                                                                                                                                                                                                                             "12pm - 9pm", "2.00pm - 10.00pm", "6.30am - 9.30pm", "7am-9pm ", 
                                                                                                                                                                                                                                             "8.00am - 3.00pm", "8.00am - 4.00pm", "8:15am - 5pm", "8am - 6pm", 
                                                                                                                                                                                                                                             "9.00am - 1.00pm", "9.30am - 5pm", "9.30am - 6:30pm", "9.45am - 3.45pm", 
                                                                                                                                                                                                                                             "9am - 10pm", "9am - 3.30pm", "9am - 3pm", "9am - 4pm", "9am - 5pm", 
                                                                                                                                                                                                                                             "9am - 6pm", "9am - 8pm", "9am - 9pm", "CLOSED"), class = "factor")), .Names = c("FACILITY.TYPE", 
                                                                                                                                                                                                                                                                                                                              "FACILITY.NAME", "MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", 
                                                                                                                                                                                                                                                                                                                              "FRIDAY", "SATURDAY", "SUNDAY"), class = "data.frame", row.names = c(NA, 
                                                                                                                                                                                                                                                                                                                                                                                                   -144L))

# Hi! Thanks for scrolling down, sorry to trouble you
tidydata <- function(messydata) {
  library(reshape2)
  
  suppressWarnings(melt(messydata, id.vars = 1:2, measure.vars = 3:9) -> tidyopenhours)
  tidyopenhours <- tidyopenhours[tidyopenhours$value!="CLOSED",]
  tidyopenhours <- tidyopenhours[tidyopenhours$value!="",]
  
  # Now to convert times!
  totime <- function(schtring) {
    if(is.na(strptime(schtring,"%I%p"))) {
      answer <- strptime(schtring,"%I:%M%p")
    }
    else {
      answer <- strptime(schtring,"%I%p")
    }
    answer
  }
  tidyopenhours$value <- gsub("\\.",":",tidyopenhours$value)
  tidyopenhours$value <- gsub("noon","pm",tidyopenhours$value)
  tidyopenhours$open <- lapply(strsplit(as.character(tidyopenhours$value), "-"), "[", 1)
  tidyopenhours$close <- lapply(strsplit(as.character(tidyopenhours$value), "-"), "[", 2)
  tidyopenhours$opentime <- lapply(lapply(tidyopenhours$open,totime),strftime, format="%H:%M")
  tidyopenhours$closetime <- lapply(lapply(tidyopenhours$close,totime),strftime, format="%H:%M")
  tidyopenhours
}
## That's most of the times formatted!
openvenues <- function(openinghours, thetime = as.numeric(strftime(Sys.time(),"%H")), theday=weekdays(Sys.time())) {
  thetime <- strptime(thetime,"%H")
  #print(paste("Sanity Check", thetime, theday))
  todayopen <- openinghours[toupper(weekdays(thetime))==openinghours$variable,]
  stillopen <- todayopen[thetime+1 <= strptime(todayopen$closetime,"%H:%M"),]
  opennow <- stillopen[thetime >= strptime(stillopen$opentime,"%H:%M"),]
  opennow$timeleft <- round(as.numeric(strptime(opennow$closetime, "%H:%M") - thetime)/60,1)
  opennow$timeleft <- round(as.numeric(difftime(strptime(opennow$closetime,"%H:%M"),thetime,units="hours")),1)
  opennow <- opennow[!is.na(opennow$FACILITY.NAME),]
  #print(opennow)
  opennow
}


getFacilities <- function(time=as.numeric(strftime(Sys.time(),"%H")), 
                          day=weekdays(Sys.time()))
{
  info <- openvenues(tidyopeninghours,time,day)
  info
}

plotFacilities <- function(info, time="",day=""){
  library(ggplot2)
  facilities <- ggplot(info,
                       aes(x=FACILITY.NAME, 
                           fill=FACILITY.TYPE, 
                           y=as.numeric(timeleft))) + 
    geom_bar(stat='identity') +
    theme_bw() +
    coord_flip() + 
    labs(x="Facility", y="Hours until closing", title=("Open Facilities"))
  print(facilities)
}

tidyopeninghours <- tidydata(openinghours)
